### ISSUE TITLE
Any plan to release a 2.12 version?

### ISSUE THREAD

**Issue by joan38** [btomala/teapot#1]
Hi,

Any plan to release a 2.12 version?

Cheers

**Comment by btomala** [comment]
Hi, I'm happy that someone is using it ;) give me a week or two I will prepare cross build for that.

**Comment by joan38** [comment]
:)

**Comment by btomala** [comment]
New version with updated `akka-http` just released. Also for Scala 2.12. On additional change is that `akka-http` add support for `I'm a teapot` status so I remove my customized and reuse status provided by the server.

**Comment by joan38** [comment]
Nice one thanks @btomala
